routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});


Route::resource('/articulos', App\Http\Controllers\ArticuloController::class);
Route::resource('/clientes', App\Http\Controllers\clienteController::class);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class cliente extends Model
{
    use HasFactory;
}

app/Models/producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class producto extends Model
{
    use HasFactory;
}

app/Http/Controllers/ArticuloController.php
<?php

namespace App\Http\Controllers;



use Illuminate\Http\Request;
use App\Models\producto;

class ArticuloController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $producto = producto::all();
        
        return view('articulo',compact('producto'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $producto = new producto();
        $producto->nombre = $request->nombre;
        $producto->modelo = $request->modelo;
        $producto->marca = $request->marca;
        $producto->descripcion = $request->descripcion;         
        $producto->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/clienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\cliente;
class clienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cliente = cliente::all();
        
        return view('cliente',compact('cliente'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cliente = new cliente();
        $cliente->nombre = $request->nombre;
        $cliente->apellido = $request->apellido;
        $cliente->cedula = $request->cedula;
        $cliente->tipo = $request->tipo;
        $cliente->direccion = $request->direccion;         
        $cliente->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/articulo.blade.php
@extends('dashboard')
@section('content')

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Crear
    </button>
    
  @include('modal.modalArticulo')
  
@endsection

resources/views/cliente.blade.php
@extends('dashboard')
@section('content')

@include('modal.modalCliente')
<h2>Clientes</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">apellido</th>
          <th scope="col">cedula</th>
          <th scope="col">tipo</th>
          <th scope="col">Direccion</th>
          <th scope="col">acciones</th>
        </tr>
      </thead>
      @foreach( $cliente as $clientes)
      <tbody>
        <tr>
          <td>{{$clientes->nombre}}</td>
          <td>{{$clientes->apellido}}</td>
          <td>{{$clientes->cedula}}</td>
          <td>{{$clientes->tipo}}</td>
          <td>{{$clientes->direccion}}</td>
          <td>

            <button type="button" class="btn btn-danger btn-sm">eliminar</button>
            <button type="button" class="btn btn-info btn-sm">ver</button>
            <button type="button" class="btn btn-warning btn-sm">modificar</button>
          </td>
        </tr>



      </tbody>
      @endforeach
    </table>
  </div>
@endsection

resources/views/css.blade.php
<link href="css/bootstrap.min.css" rel="stylesheet">   dashboard.css
<link href="css/dashboard.css" rel="stylesheet">

resources/views/dashboard.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Dashboard Template · Bootstrap v5.3</title>

  

    @include('css')

    

<link href="css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <!-- Favicons -->
    
    
<link rel="apple-touch-icon" href="http://localhost/LR/formulario_laravel/public/img/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="http://localhost/LR/formulario_laravel/public/img/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="http://localhost/LR/formulario_laravel/public/img/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="http://localhost/LR/formulario_laravel/public/json/manifest.json">
<link rel="mask-icon" href="http://localhost/LR/formulario_laravel/public/img/apple-touch-icon.pngsafari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="http://localhost/LR/formulario_laravel/public/img/apple-touch-icon.pngfavicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">PremiumSoft Falcón </a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
@include('includes.menu')

     @yield('content')

      

      
    </main>
  </div>
</div>
@include('js')

   
  </body>
</html>

resources/views/includes/menu.blade.php
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url('/articulos') }}">
    <span data-feather="shopping-cart" class="align-text-bottom"></span>
   
    Crear Productos
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <span data-feather="dollar-sign" class="align-text-bottom"></span>
    Venta
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url('/clientes') }}">
    <span data-feather="users" class="align-text-bottom"></span>
    Crear clientes
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <span data-feather="file-text" class="align-text-bottom"></span>
    Reportes
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <span data-feather="clipboard" class="align-text-bottom"></span>
   Crear Modelo 
  </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="#">
      <span data-feather="book-open" class="align-text-bottom"></span>
     Crear Marca 
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">
      <span data-feather="dollar-sign" class="align-text-bottom"></span>
     Tasa 
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">
      <span data-feather="home" class="align-text-bottom"></span>
    Moneda 
    </a>
  </li>
</ul>



</div>
</nav>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1 class="h2">PANEL</h1>
<div class="btn-toolbar mb-2 mb-md-0">
<div class="btn-group me-2">
  <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
  <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
</div>
<button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
  <span data-feather="calendar" class="align-text-bottom"></span>
  This week
</button>
</div>
</div>
<!-- Button trigger modal -->

resources/views/js.blade.php
<script src="js/feather.min.js"></script>
<script src="js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script src="js/dashboard.js"></script>
<script src="js/docsearch.min.js"></script>
<script src="js/jquery-3.2.1.slim.min.js"></script>


<script src="js/bootstrap.bundle.js"></script>
<script src="js/bootstrap.bundle.js.map"></script>
<script src="js/jquery-3.2.1.slim.min.jss"></script>
<script src="js/bootstrap.bundle.min.js"></script>
<script src="js/bootstrap.esm.js"></script>
<script src="js/bootstrap.esm.js.map"></script>
<script src="js/bootstrap.esm.min.js"></script>
<script src="js/bootstrap.esm.min.js.map"></script>
<script src="js/bootstrap.js"></script>

<script src="js/bundle.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
</script>

  <script src="js/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
  <script src="js/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous">
</script><script src="js/dashboard.js"></script>

resources/views/modal/modalArticulo.blade.php
  <!-- Modal -->
  <h2>Productos</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">modelo</th>
          <th scope="col">marca</th>
          <th scope="col">descripcion</th>
          <th scope="col">acciones</th>
        </tr>
      </thead>
      @foreach( $producto as $productos)
      <tbody>
        <tr>
          <td>{{$productos->nombre}}</td>
          <td>{{$productos->modelo}}</td>
          <td>{{$productos->marca}}</td>
          <td>{{$productos->descripcion}}</td>
          <td>

            <button type="button" class="btn btn-danger btn-sm">eliminar</button>
            <button type="button" class="btn btn-info btn-sm">ver</button>
            <button type="button" class="btn btn-warning btn-sm">modificar</button>
          </td>
        </tr>



      </tbody>
      @endforeach
    </table>
  </div>
  
  
  
  <div class="modal fade  " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog cuadro1">
      <div class="modal-content ">
        <div class="modal-header cuadro1 ">
          <h5 class="modal-title" id="exampleModalLabel">Descripción Articulo</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div> 
        <div class="modal-body cuadro">
          <form class="form-inline"  action="{{ route('articulos.store') }}" method="POST">
            @csrf
            <div class="form-group">
              <label for="email"></label>
              <input type="text" class="form-control" id="nombre " name="nombre" placeholder="Nombre">
            </div>
            <div class="form-group">
              <label for="pwd"></label>
              <input type="text" class="form-control" id="modelo"   name="modelo" placeholder="Modelo">
            </div>
            <div class="form-group">
              <label for="pwd"></label>
              <input type="text" class="form-control" id="marca"    name="marca" placeholder="Marca">
            </div>
            <div class="mb-3">
              <label for="pwd"></label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"  name="descripcion" placeholder="Descripción "></textarea>
            </div>
            <button type="submit"  class="btn btn-secondary">Save</button>
          </form>
        </div>
        
      </div>
    </div>




    
  </div>









<style>


.cuadro{

  background: #0F2027;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #2C5364, #203A43, #0F2027);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #2C5364, #203A43, #0F2027); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}

.cuadro1{
  background: #0F2027;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #2C5364, #203A43, #0F2027);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #2C5364, #203A43, #0F2027); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

}


</style>

resources/views/modal/modalCliente.blade.php
 
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#cliente">
  Crear
</button>
<h2>Clientes</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">apellido</th>
          <th scope="col">cedula</th>
          <th scope="col">tipo</th>
          <th scope="col">Direccion</th>
          <th scope="col">acciones</th>
        </tr>
      </thead>
      @foreach( $cliente as $clientes)
      <tbody>
        <tr>
          <td>{{$clientes->nombre}}</td>
          <td>{{$clientes->apellido}}</td>
          <td>{{$clientes->cedula}}</td>
          <td>{{$clientes->tipo}}</td>
          <td>{{$clientes->direccion}}</td>
          <td>

            <button type="button" class="btn btn-danger btn-sm">eliminar</button>
            <button type="button" class="btn btn-info btn-sm">ver</button>
            <button type="button" class="btn btn-warning btn-sm">modificar</button>
          </td>
        </tr>



      </tbody>
      @endforeach
    </table>
  </div>
 
 <!-- Modal -->
  <div class="modal fade  " id="cliente" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog cuadro1">
      <div class="modal-content ">
        <div class="modal-header cuadro1 ">
          <h5 class="modal-title" id="exampleModalLabel">Descripción Cliente</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div> 
        <div class="modal-body cuadro">
          <form class="form-inline"  action="{{ route('clientes.store') }}" method="POST">
            @csrf
            <div class="form-group">
              <label for="email"></label>
              <input type="text" class="form-control" id="nombre " name="nombre" placeholder="Nombre">
            </div>
            <div class="form-group">
              <label for="pwd"></label>
              <input type="text" class="form-control" id="apellido"   name="apellido" placeholder="Apellido">
            </div>
            <div class="form-group">
                <label for="pwd"></label>
                <input type="text" class="form-control" id="cedula"   name="cedula" placeholder="cedula">
              </div>
            <div class="form-group">
              <label for="pwd"></label>
              <input type="text" class="form-control" id="tipo"    name="tipo" placeholder="Tipo">
            </div>
            <div class="mb-3">
              <label for="pwd"></label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"  name="direccion" placeholder="Direccion "></textarea>
            </div>
            <button type="submit"  class="btn btn-secondary">Save</button>
          </form>
        </div>
     
      </div>
    </div>


    <style>


      .cuadro{
      
        background: #0F2027;  /* fallback for old browsers */
      background: -webkit-linear-gradient(to right, #2C5364, #203A43, #0F2027);  /* Chrome 10-25, Safari 5.1-6 */
      background: linear-gradient(to right, #2C5364, #203A43, #0F2027); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
      }
      
      .cuadro1{
        background: #0F2027;  /* fallback for old browsers */
      background: -webkit-linear-gradient(to right, #2C5364, #203A43, #0F2027);  /* Chrome 10-25, Safari 5.1-6 */
      background: linear-gradient(to right, #2C5364, #203A43, #0F2027); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
      
      }
      
      
      </style>